clear; close all; clc;

% load the functions of PRESTUS and kWave

cd /home/affneu/kenvdzee/Documents/PRESTUS/
addpath('functions')
addpath(genpath('toolboxes'))
cd /home/affneu/kenvdzee/Documents/phd_1_analysis/simulations/nico_sham_simulations/

%% params

% equipment params (values for 75mm Imasonics transducer)
source_freq_hz = 300e3;
Elements_ID_mm = [10.0, 22.3, 30.0, 36.3, 41.7, 46.5, 51.0, 55.1, 58.9, 62.5];
Elements_OD_mm = [21.3, 29.1, 35.3, 40.7, 45.6, 50.0, 54.1, 58.0, 61.6, 65.0];
curv_radius_mm = 75;
source_phase_rad = [0, 360, 53.59, 114.16, 183.54, 188.26, 218.24, 188.01, 203, 104.26];
dist_to_exit_plane = 7;
source_amp = 117192;

% space params
grid_dims = [144, 144, 256];
grid_step_m = 0.5/1000;
grid_size = grid_dims*grid_step_m;
axial_position = (1:grid_dims(3))*(grid_step_m*1000);
axial_position = axial_position';
axial_position = axial_position + dist_to_exit_plane;

% water params
sound_speed = 1500;
density = 994;

% design params
expected_focal_distance_mm = 67.4;
voxels_from_edge = 11;
trans_pos = [72 72 voxels_from_edge];
focus_pos = [72 72 round(voxels_from_edge + expected_focal_distance_mm/(grid_step_m*1000))];

%% optimize phases (active condition)

opt_limits = [axial_position(2,1), axial_position(end,1)];

desired_function = create_boxcar(expected_focal_distance_mm, 20, axial_position, 0, 200);

% create the weights function
[flhm_center, flhm_center_index] = get_flhm_center_position( ...
    axial_position, ...
    desired_function ...
    );
weights = normpdf_nostatstoolbox( ...
    axial_position(:,1), ...
    axial_position(flhm_center_index,1), ...
    axial_position(flhm_center_index,1)/.5 ...
    );

% bring parameters in PRESTUS-readable format
parameters = [];
parameters.transducer.curv_radius_mm = curv_radius_mm;
parameters.transducer.Elements_ID_mm = Elements_ID_mm;
parameters.transducer.Elements_OD_mm = Elements_OD_mm;
parameters.transducer.n_elements     = numel(Elements_ID_mm);
parameters.transducer.source_freq_hz = source_freq_hz;
parameters.medium.water.sound_speed  = sound_speed;
parameters.medium.water.density      = density;

optimize_phases = @(phases_and_velocity) phase_optimization_annulus_full_curve( ...
    phases_and_velocity(1:parameters.transducer.n_elements-1), ...
    parameters, ...
    phases_and_velocity(parameters.transducer.n_elements),...
    axial_position, ...
    desired_function, ...
    0, ...
    opt_limits, ...
    weights);

rng(100,'twister') % setting seed for consistency

velocity = source_amp(1)/(parameters.medium.water.density*parameters.medium.water.sound_speed);   % [m/s]
func = optimize_phases;
x0 = [randi(360, [1 parameters.transducer.n_elements - 1])/180*pi velocity];
lb = zeros(1,parameters.transducer.n_elements);
ub = [2*pi*ones(1,parameters.transducer.n_elements - 1) 0.2];
options = setoptimoptions( ...
    'popsize',1000, ...
    'FinDiffType', 'central', ...
    'MaxFunEvals', 1e6, ...
    'MaxIter', 1e7 ...
    );
[opt_phases_and_velocity, ~, ~, ~] = minimize(func, x0, [],[],[],[],lb, ub, [], options);

% note: I adjusted the phase_optimization_annulus_full_curve function so
% that it returns the axial intensity as the last output parameter
[~, ~, ~, h, i_axial_oneil] = phase_optimization_annulus_full_curve( ...
    opt_phases_and_velocity(1:parameters.transducer.n_elements-1), ...
    parameters, ...
    opt_phases_and_velocity(parameters.transducer.n_elements),...
    axial_position, ...
    desired_function, ...
    1, ...
    opt_limits, ...
    weights ...
    );  

close(h);

%% optimize phases (sham condition)

% manual step: set the axial position in mm from which point on the
% intensity should ideally be zero
intensity_cutoff = 49;

desired_function_sham = i_axial_oneil .* single(axial_position < intensity_cutoff); % near field

optimize_phases = @(phases_and_velocity) phase_optimization_annulus_full_curve( ...
    phases_and_velocity(1:parameters.transducer.n_elements-1), ...
    parameters, ...
    phases_and_velocity(parameters.transducer.n_elements),...
    axial_position, ...
    desired_function_sham, ...
    0, ...
    opt_limits, ...
    weights);

velocity = source_amp(1)/(parameters.medium.water.density*parameters.medium.water.sound_speed);   % [m/s]
func = optimize_phases;
x0 = [randi(360, [1 parameters.transducer.n_elements-1])/180*pi velocity];
lb = zeros(1,parameters.transducer.n_elements);
ub = [2*pi*ones(1,parameters.transducer.n_elements-1) 0.2];
options = setoptimoptions( ...
    'popsize',1000, ...
    'FinDiffType', 'central', ...
    'MaxFunEvals', 1e6, ...
    'MaxIter', 1e7 ...
    ); % number of initializations [, 'TolCon', 1e-8]
[opt_phases_and_velocity, min_err, ~, output] = minimize(func, x0, [],[],[],[],lb, ub, [], options);

% note: I adjusted the phase_optimization_annulus_full_curve function so
% that it returns the axial intensity as the last output parameter
[~, ~, ~, h, i_axial_oneil_sham] = phase_optimization_annulus_full_curve( ...
    opt_phases_and_velocity(1:parameters.transducer.n_elements-1), ...
    parameters, ...
    opt_phases_and_velocity(parameters.transducer.n_elements),...
    axial_position, ...
    desired_function_sham, ...
    1, ...
    opt_limits, ...
    weights ...
    );  

close(h);

%% plot the optimization results

figure('Position', [100, 100, 1000, 400]);
plot(axial_position, i_axial_oneil, 'LineWidth', 2); % NOTE: 0 in axial position should be surface of transducer! therefore needs correcting term
hold on;
plot(axial_position, i_axial_oneil_sham, 'LineWidth', 2);
xticks(linspace(0, max(axial_position), 10));
ylim([0 max(desired_function)]);
xlabel('focal axis (mm)');
ylabel('intensity');
legend('active', 'sham');