function [cfg] = bch_cmbecho_to_4D(cfg)
%BCH_CMBECHO_TO_4D combined echo 3D nifits to 4D
%   Combines the 3D NIFTI files generated by bch_me_combine_echoes to make
%   4D NIFITI files for each run
%
% Written by Vaibhav Arya. January 2020

direc = fullfile(cfg.dir.func);
img_prefix = ['^',cfg.prefix.func,cfg.prefix.img];

run = cfg_getfile('FPList',direc,'any',img_prefix);
dt = 0; % set to 0 so that output data type is same as input data type

% determine filename of new 4D file
fileNames = spm_select('FPList',direc);
thisFileName = fileNames(1,:);

appendloc = strfind(thisFileName,'0001');
appendtext = '.nii';
fname = [thisFileName(1:appendloc-1) appendtext];

% merge 3D files into 4D
spm_file_merge(run, fname, dt);
delete(run{:});

% repeat the same steps for separate echo's
for ee = 1:cfg.me.nechoes
    
    echo_dir = fullfile(direc,[cfg.me.dir_prefix,sprintf('%02d',ee)]);
    run = cfg_getfile('FPList',echo_dir,'any',img_prefix);
    dt = 0; % set to 0 so that output data type is same as input data type
    
    % determine filename of new 4D file
    fileNames = spm_select('FPList',echo_dir);
    thisFileName = fileNames(1,:);
    
    appendloc = strfind(thisFileName,'0001');
    appendtext = '.nii';
    fname = [thisFileName(1:appendloc-1) appendtext];
    
    spm_file_merge(run, fname, dt);
    delete(run{:});
    
end

end

