# Location of stored data
data_path: /project/3025011.02/bids/
seg_path: /project/3025011.02/TUS_simulations/segmentation_data/
simnibs_bin_path: /home/affneu/kenvdzee/.conda/envs/simnibs_env/bin/
ld_library_path: /home/affneu/kenvdzee/.conda/envs/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/../../external/lib/linux
subject_subfolder: 1
output_location: /project/3025011.02/TUS_simulations/planning/target_3_2/
stimulation_target: target_3_2

overwrite_simnibs: 0

# Picks a specific GPU that always works for thermal simulations
hcp_gpu: "gpu:1"
hcp_partition: gpu40g

# Structure of subfolders containing T1 and T1 images
## It is easier to store the subject data of each participant in an individual subfolder
t1_path_template: sub-%1$03d/ses-mri01/anat/*mprage_T1w.nii.gz
t2_path_template: sub-%1$03d/ses-mri01/anat/*sagisop2ellscan_T2w.nii.gz

transducer: 
  n_elements: 30 # number of elements in the transducer
  Elements_ID_mm: [10, 13.7667, 17.5333, 22.3, 24.5667, 26.8333, 30, 31.7667, 33.5333, 36.3, 37.7667, 39.2333, 41.7, 43.0, 44.3, 46.5, 47.6667, 48.8333, 51, 52.0333, 53.0667, 55.1, 56.0667, 57.0333, 58.9, 59.8, 60.7, 62.5, 63.3333, 64.1667]
  Elements_OD_mm: [13.7667, 17.5333, 21.3, 24.5667, 26.8333, 29.1, 31.7667, 33.5333, 35.3, 37.7667, 39.2333, 40.7, 43.0, 44.3, 45.6, 47.6667, 48.8333, 50, 52.0333, 53.0667, 54.1, 56.0667, 57.0333, 58, 59.8, 60.7, 61.6, 63.3333, 64.1667, 65]
  curv_radius_mm: 75 # radius of curvature of the bowl 
  dist_to_plane_mm: 65.3 # distance to the transducer plane from the geometric focus
  source_amp: 50000 # 36510 # [Pa]
  source_phase_deg: [0, 159.41, 211.42, 158.69, 193.9, 254.95, 208.03, 121.69, 98.44, 227.43, 272.34, 280.79, 215.57, 272.53, 107.87, 135.84, 111.07, 122.53, 235.89, 177.02, 212.75, 260.25, 106.03, 106.87, 121.03, 135.26, 156.83, 182.16, 182.79, 237.82] # source phase [deg]
  pos_t1_grid: [136,182,262]
  source_freq_hz: 300e3 # [Hz] the central frequency

focus_pos_t1_grid: [123,172,211]

# Not save mat files to save storage
savemat: 0
ld_library_path: /home/affneu/kenvdzee/.conda/envs/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/../../external/lib/linux

transducer_from_localite: 0 # should we load the transducer locations from the localite file(s) 

using_donders_hpc: 1
overwrite_simnibs: 0
use_forceqform: 1

run_posthoc_water_sims: 0
run_heating_sims: 1
run_acoustic_sims: 1

# Stimulate the next location
subsequent_heating_config: [config_kenneth_phd_1_defocussed_2_PCD15287_01002.yaml, config_kenneth_phd_1_defocussed_3_PCD15287_01001.yaml, config_kenneth_phd_1_defocussed_4_PCD15287_01002.yaml, config_kenneth_phd_1_defocussed_5_PCD15287_01001.yaml, config_kenneth_phd_1_defocussed_6_PCD15287_01002.yaml]

# Parameters for thermal simulations
thermal:
  duty_cycle: 0.2
  n_trials: 80
  sim_time_steps: 0.5
  post_stim_dur: 20
  post_stim_time_step_dur: 0.5
  pri_duration: 0.5
  equal_steps: 0