---
title: "Simple learning model"
output: html_document
---

This is a first attempt at a pipeline to run learning models on the data of phd_task_1.

```{r}
library('rstan')

```

R-Stan options
```{r}
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

```{r}
AmydACC_data <- read.csv('/Users/kenneth.van.der.zee/Documents/phd_1_analysis/pre-processed/modelling_data/combined_dataframe_binary.csv', sep = ';')
```

# Prepare stan data
```{r}
# To be used dataset
AmydACC_test_data <- subset(AmydACC_data)
names(AmydACC_test_data)[names(AmydACC_test_data) == 'trial'] <- 'N'

# Prepare data for stan
stan_data_amydacc <- list(
  N = nrow(AmydACC_test_data),
  S = length(unique(AmydACC_test_data$subject_id)),
  subject_id = as.integer(AmydACC_test_data$subject_id - min(AmydACC_test_data$subject_id) + 1),
  subjectively_correct_int = AmydACC_test_data$subjectively_correct_int,
  objectively_correct_int = AmydACC_test_data$objectively_correct_int,
  stimuli_type = AmydACC_test_data$valence
)

```

```{r}
# Example data
data <- data.frame(
  trial = 1:10,
  subjectively_correct_int = c(0, 1, 0, 1, 1, 0, 1, 1, 0, 1),
  objectively_correct_int = c(0, 1, 0, 1, 0, 0, 1, 1, 0, 1),
  stimuli_type = c(1, 1, 3, 3, 1, 1, 3, 3, 1, 3),
  subject_id = c(901, 902, 903, 904, 905, 906, 907, 908, 909, 910)
)

# Prepare data for Stan
stan_data <- list(
  N = nrow(data),
  S = length(unique(data$subject_id)),
  subject_id = as.integer(data$subject_id - min(data$subject_id) + 1),
  subjectively_correct_int = data$subjectively_correct_int,
  objectively_correct_int = data$objectively_correct_int,
  stimuli_type = data$stimuli_type
)
```

```{r}
fit <- stan(file = 'AmydACC_model_1.stan', data = stan_data_amydacc)
```

```{r}
print(fit)
```

```{r}
# Extract samples
samples <- extract(fit)

# Calculate the average learning rates and initial expected values across subjects
mean_alpha0 <- mean(samples$alpha0)
mean_alpha1 <- mean(samples$alpha1)
mean_V1_type1 <- mean(samples$V1_type1)
mean_V1_type3 <- mean(samples$V1_type3)

# Print the averages
cat("Average learning rate for stimulus type 1:", mean_alpha0, "\n")
cat("Average learning rate for stimulus type 3:", mean_alpha1, "\n")
cat("Average initial expected value for stimulus type 1:", mean_V1_type1, "\n")
cat("Average initial expected value for stimulus type 3:", mean_V1_type3, "\n")
```

```{r}
print('this is just here so I can run all previous blocks')
```